name: db_viewer
description: A new Flutter project.
version: 1.0.0
homepage: https://github.com/vanlooverenkoen/db_viewer/db_viewer

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

flutter:

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
